name: Run tests

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    # Code Checkout 
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.11
      uses: actions/setup-python@v2
      with:
        python-version: 3.11
    
    - name: Install dependencies
      run: |
        pip install sqlalchemy pandas numpy

    - name: Run tests
      run: |
        echo "=== Executing pipeline ==="
        
        # Execute your pipeline
        python ./project/data/pipeline.py
        
        # Validate the output file(s)
        if [ -f "./project/data/nuremberg_stops_immoscout.db" ]; then
          echo "Output file(s) exist."
        else
          echo "Output file(s) not found."
        fi
        
        echo "=== Running Tests ==="
        python ./project/test.py
        
        echo "All testd done"
